CREATE TABLE blog_post
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    text         VARCHAR(2000),
    created_date TIMESTAMP,
    CONSTRAINT pk_blogpost PRIMARY KEY (id)
);