CREATE TABLE comment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author       VARCHAR(255),
    text      VARCHAR(255),
    created_date TIMESTAMP,
    blog_post_id BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_BLOGPOST FOREIGN KEY (blog_post_id) REFERENCES blog_post (id);