INSERT INTO BLOG_POST (CREATED_DATE,TITLE, TEXT) VALUES
	 ('2023-01-12 19:36:54.344','What is Lorem Ipsum?','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris suscipit tellus leo, pretium consequat tellus sollicitudin non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque sed arcu tortor. Integer orci elit, maximus eu ex ac, congue viverra sem. Nunc eu tellus ac enim sagittis tempor eget vitae augue. Phasellus nibh sem, tincidunt ac iaculis quis, interdum ut nibh. Fusce eget viverra eros. Fusce et sem suscipit, pharetra massa ut, dictum dui. Ut eu auctor nunc. Ut augue dolor, varius scelerisque mollis maximus, viverra sed augue.

Ut volutpat risus non laoreet efficitur. Praesent ac mi vel libero fermentum hendrerit sit amet vitae ex. Aenean faucibus, nisi ac porttitor lobortis, arcu erat volutpat magna, a euismod nunc est non urna. In vel ligula a eros dignissim egestas ut et sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum sit amet mauris felis. Aenean tincidunt, dui eu porta varius, purus massa bibendum purus, at dictum dui mauris nec nisl. Sed in orci dignissim, pulvinar magna quis, finibus lectus. Etiam commodo lectus et enim pulvinar, sit amet auctor risus tempus. Phasellus maximus tempus arcu sit amet tincidunt. Donec ac vehicula dui. Fusce dignissim congue sodales. Curabitur venenatis velit sed fringilla cursus.

Vestibulum eget faucibus mauris. Donec pulvinar nisi dictum blandit euismod. Suspendisse ac purus fringilla, condimentum lacus a, hendrerit magna. Phasellus euismod, massa non laoreet ornare, odio nisl sagittis libero, quis vehicula quam est at turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec laoreet ipsum vel mauris euismod luctus. Praesent id finibus lacus.'),
	 ('2023-01-12 19:36:54.447','Where does it come from?','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras blandit vitae urna vitae facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque quis cursus lorem, ornare condimentum felis. Aliquam sit amet erat tortor. Nulla et nulla facilisis, varius erat iaculis, tincidunt odio. Suspendisse vitae lacus quis tellus dignissim congue at non est. Suspendisse sollicitudin ultrices metus, et malesuada est dignissim tristique. Praesent at aliquet eros, eget scelerisque lacus. Donec ut enim sed justo volutpat luctus.

Praesent efficitur nibh ac interdum dapibus. Vestibulum a blandit arcu. Morbi tristique, leo at lacinia accumsan, ligula libero porttitor mi, vitae bibendum purus lorem vitae nulla. Pellentesque lacus sem, placerat sed interdum eu, sollicitudin vitae mi. Vivamus elit felis, ultrices nec imperdiet vel, lacinia non diam. Nunc sit amet finibus nisl. Nullam ligula metus, maximus imperdiet urna vel, dapibus accumsan dui. Nam sit amet pulvinar mi. Morbi commodo tellus nec diam consectetur, a posuere metus feugiat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id ligula eget est suscipit vulputate in a nibh. Phasellus condimentum, justo gravida vulputate imperdiet, dui elit gravida ex, vel scelerisque lorem risus nec diam. Mauris quis venenatis tortor. Phasellus eget mi at odio ultrices facilisis.

Donec vestibulum elit sed massa maximus convallis. Duis venenatis, velit sit amet lobortis maximus, velit ligula egestas urna, a accumsan metus turpis quis sem. Sed id eros pharetra, mollis libero at, fermentum tellus. Aenean eu volutpat nisi, sit amet pellentesque tellus. Fusce mollis sem velit, quis ultrices nisl vestibulum at. Phasellus interdum, urna eget elementum tempor, dolor augue placerat lorem, quis tincidunt est lacus vitae leo. Nunc aliquam at turpis ac mattis. Quisque molestie ornare lectus quis posuere.');

